### ISSUE TITLE
count numbers does not align vertically

### ISSUE THREAD

**Issue by ghost** [CROSP/accordion-categories#1]
Hello,
I tried your Accordion Categories plugin.
I think it is very simple and useful.

I have one question.

In the screenshot below,

https://ps.w.org/accordion-categories/assets/screenshot-1.png?rev=1617807

All the count numbers are aligned vertically.

But these numbers did not aligned vertically in my test.
Do you have any demo site that I can see the same image as screenshot ?

**Comment by ghost** [comment]
I have done several tests and found that this symptom depends on the WP theme.
In my test, this symptom occurs with the following themes.
Twenty Sixteen
Twenty Fifteen

But, in the latest theme,
Twenty Seventeen
the problem did not happen.
I hope this information will help you.

**Comment by CROSP** [comment]
@hiromi3 , Thank you so much for your response, I will have a look and try to fix it as soon as possible. Your information is very helpful.
I will do my best to fix this problem, I guess the problem is the load order of CSS files. 

Thanks, if you find any other issues, please let me know.

**Comment by CROSP** [comment]
@hiromi3 , could you please post a screenshot of the problem ?
Do you mean this problem ? 
<img width="365" alt="screen shot 2017-03-25 at 10 17 01 am" src="https://cloud.githubusercontent.com/assets/5072318/24320760/6eebf1e8-1144-11e7-9998-86ffb3b34228.png">

**Comment by ghost** [comment]
Hello,
Yes, I mean that.
Is it a normal behavior of your plugin?

**Comment by CROSP** [comment]
@hiromi3 of course not) I have just fixed this issue and uploaded the new plugin version https://wordpress.org/plugins/accordion-categories/ . Please test it and let me know if it works. 
Thanks

**Comment by ghost** [comment]
Thank you for your quick action.
I tested the Accordion Categories 1.2 on the following themes.
Twenty Thirteen       x    not aligned vertically
Twenty Fourteen      x    only top level items are shown and no sub items are shown
Twenty Fifteen 	 o   vertically aligned
Twenty Sixteen         o   vertically aligned
Twenty Seventeen    o   vertically aligned

I am using Twenty Seventeen, so my issue was solved.

**Comment by CROSP** [comment]
@hiromi3 thank you for your help. Appreciate it. 
But as far as there are a lot of themes available and usually custom themes are used this is just the problem of a CSS file used along with a theme. And for example in case of using `important` somewhere in a theme css file will override the plugin style. 
And in addition I have specific colors used for this plugin. So anyway one is going to override the plugin styles. 
As for Twenty Fourteen it is interesting. I will take a look. 
Thank you, if you find any other issues please feel free to open an issue.
